'use strict';

var SIGNS = [
  {mask: /Na/g, en: 'sodium'},
  {mask: /O/g, en: 'oxygen'},
  {mask: /Ca/g, en: 'xalcium'},
  {mask: /Cr/g, en: 'chromium'},


  {mask: /Ar/g, en: 'argon', exp: 'Ar'},
  {mask: /Am/g, en: 'americium', exp: 'Am'},
  {mask: /Ar/g, en: 'arsenic', exp: 'Ar'},
  {mask: /At/g, en: 'astatine', exp: 'At'},
  {mask: /Au/g, en: 'gold', exp: 'Au'},
  {mask: /B/g, en: 'boron', exp: 'B'},
  {mask: /Ba/g, en: 'barium', exp: 'Ba'},
  {mask: /Bh/g, en: 'bohrium', exp: 'Bh'},
  {mask: /Bi/g, en: 'bismuth', exp: 'Bi'},
  {mask: /Br/g, en: 'bromine', exp: 'Br'},
  {mask: /Cd/g, en: 'cadmium', exp: 'Cd'},
  {mask: /Ce/g, en: 'cerium', exp: 'Ce'},
  {mask: /Co/g, en: 'cobalt', exp: 'Co'},
  {mask: /Cl/g, en: 'chlorine', exp: 'Cl'},
  {mask: /Cs/g, en: 'cesium', exp: 'Cs'},
  {mask: /Cu/g, en: 'copper', exp: 'Cu'},
  {mask: /Db/g, en: 'dubnium', exp: 'Db'},
  {mask: /Ds/g, en: 'darmstadtium', exp: 'Ds'},
  {mask: /Dy/g, en: 'dysprosium', exp: 'Dy'},
  {mask: /Er/g, en: 'erbium', exp: 'Er'},
  {mask: /einsteinium/g, en: 'Es', exp: 'Es'},
  {mask: /europium/g, en: 'Eu', exp: 'Eu'},
  {mask: /fluorine/g, en: 'F', exp: 'F'},
  {mask: /fermium/g, en: 'Fm', exp: 'Fm'},
  {mask: /francium/g, en: 'Fr', exp: 'Fr'},
  {mask: /gallium/g, en: 'Ga', exp: 'Ga'},
  {mask: /gadolinium/g, en: 'Gd', exp: 'Gd'},
  {mask: /germanium/g, en: 'Ge', exp: 'Ge'},
  {mask: /hafnium/g, en: 'Hf', exp: 'Hf'},
  {mask: /mercury/g, en: 'Hg', exp: 'Hg'},
  {mask: /holmium/g, en: 'Ho', exp: 'Ho'},
  {mask: /hassium/g, en: 'Hs', exp: 'Hs'},
  {mask: /iodine/g, en: 'I', exp: 'I'},
  {mask: /indium/g, en: 'In', exp: 'In'},
  {mask: /iridium/g, en: 'Ir', exp: 'Ir'},
  {mask: /potassium/g, en: 'K', exp: 'K'},
  {mask: /krypton/g, en: 'Kr', exp: 'Kr'},
  {mask: /lanthanum/g, en: 'La', exp: 'La'},
  {mask: /lithium/g, en: 'Li', exp: 'Li'},
  {mask: /lutetium/g, en: 'Lu', exp: 'Lu'},
  {mask: /mendelevium/g, en: 'Md', exp: 'Md'},
  {mask: /manganese/g, en: 'Mn', exp: 'Mn'},
  {mask: /molybdenum/g, en: 'Mo', exp: 'Mo'},
  {mask: /meitnerium/g, en: 'Mt', exp: 'Mt'},
  {mask: /nitrogen/g, en: 'N', exp: 'N'},
  {mask: /niobium/g, en: 'Nb', exp: 'Nb'},
  {mask: /neodymium/g, en: 'Nd', exp: 'Nd'},
  {mask: /neon/g, en: 'Ne', exp: 'Ne'},
  {mask: /nickel/g, en: 'Ni', exp: 'Ni'},
  {mask: /nobelium/g, en: 'No', exp: 'No'},
  {mask: /neptunium/g, en: 'Np', exp: 'Np'},
  {mask: /osmium/g, en: 'Os', exp: 'Os'},
  {mask: /phosphorus/g, en: 'P', exp: 'P'},
  {mask: /protactinium/g, en: 'Pa', exp: 'Pa'},
  {mask: /lead/g, en: 'Pb', exp: 'Pb'},
  {mask: /palladium/g, en: 'Pd', exp: 'Pd'},
  {mask: /promethium/g, en: 'Pm', exp: 'Pm'},
  {mask: /polonium/g, en: 'Po', exp: 'Po'},
  {mask: /praseodymium/g, en: 'Pr', exp: 'Pr'},
  {mask: /platinum/g, en: 'Pt', exp: 'Pt'},
  {mask: /plutonium/g, en: 'Pu', exp: 'Pu'},
  {mask: /radium/g, en: 'Ra', exp: 'Ra'},
  {mask: /rutherfordium/g, en: 'Rf', exp: 'Rf'},
  {mask: /ruthenium/g, en: 'Ru', exp: 'Ru'},
  {mask: /sulfur/g, en: 'S', exp: 'S'},
  {mask: /uranium/g, en: 'U', exp: 'U'},
  {mask: /zinc/g, en: 'Zn', exp: 'Zn'},
  {mask: /zirconium/g, en: 'Zr', exp: 'Zr'}

  ];




module.exports = SIGNS;