'use strict';

var SIGNS = [
  {mask: /sodium/g, latex: 'Na', exp: 'Na'},
  {mask: /oxygen/g, latex: 'O', exp: 'O'},
  {mask: /аluminum/g, latex: 'Al', exp: 'Al'},
  {mask: /hydrogen/g, latex: 'H', exp: 'H'},
  {mask: /lithium/g, latex: 'Li', exp: 'Li'},
  {mask: /helium/g, latex: 'He', exp: 'He'},
  {mask: /magnesium/g, latex: 'Mg', exp: 'Mg'},
  {mask: /xalcium/g, latex: 'Ca', exp: 'Ca'},
  {mask: /chromium/g, latex: 'Cr', exp: 'Cr'},
  {mask: /potassium/g, latex: 'K', exp: 'K'},
  {mask: /iron/g, latex: 'Fe', exp: 'Fe'},
  {mask: /carbon/g, latex: 'C', exp: 'C'},



  {mask: /argon/g, latex: 'Ar', exp: 'Ar'},
  {mask: /americium/g, latex: 'Am', exp: 'Am'},
  {mask: /arsenic/g, latex: 'Ar', exp: 'Ar'},
  {mask: /astatine/g, latex: 'At', exp: 'At'},
  {mask: /gold/g, latex: 'Au', exp: 'Au'},
  {mask: /boron/g, latex: 'B', exp: 'B'},
  {mask: /barium/g, latex: 'Ba', exp: 'Ba'},
  {mask: /bohrium/g, latex: 'Bh', exp: 'Bh'},
  {mask: /bismuth/g, latex: 'Bi', exp: 'Bi'},
  {mask: /bromine/g, latex: 'Br', exp: 'Br'},
  {mask: /cadmium/g, latex: 'Cd', exp: 'Cd'},
  {mask: /cerium/g, latex: 'Ce', exp: 'Ce'},
  {mask: /cobalt/g, latex: 'Co', exp: 'Co'},
  {mask: /chlorine/g, latex: 'Cl', exp: 'Cl'},
  {mask: /cesium/g, latex: 'Cs', exp: 'Cs'},
  {mask: /copper/g, latex: 'Cu', exp: 'Cu'},
  {mask: /dubnium/g, latex: 'Db', exp: 'Db'},
  {mask: /darmstadtium/g, latex: 'Ds', exp: 'Ds'},
  {mask: /dysprosium/g, latex: 'Dy', exp: 'Dy'},
  {mask: /erbium/g, latex: 'Er', exp: 'Er'},
  {mask: /einsteinium/g, latex: 'Es', exp: 'Es'},
  {mask: /europium/g, latex: 'Eu', exp: 'Eu'},
  {mask: /fluorine/g, latex: 'F', exp: 'F'},
  {mask: /fermium/g, latex: 'Fm', exp: 'Fm'},
  {mask: /francium/g, latex: 'Fr', exp: 'Fr'},
  {mask: /gallium/g, latex: 'Ga', exp: 'Ga'},
  {mask: /gadolinium/g, latex: 'Gd', exp: 'Gd'},
  {mask: /germanium/g, latex: 'Ge', exp: 'Ge'},
  {mask: /hafnium/g, latex: 'Hf', exp: 'Hf'},
  {mask: /mercury/g, latex: 'Hg', exp: 'Hg'},
  {mask: /holmium/g, latex: 'Ho', exp: 'Ho'},
  {mask: /hassium/g, latex: 'Hs', exp: 'Hs'},
  {mask: /iodine/g, latex: 'I', exp: 'I'},
  {mask: /indium/g, latex: 'In', exp: 'In'},
  {mask: /iridium/g, latex: 'Ir', exp: 'Ir'},
  {mask: /potassium/g, latex: 'K', exp: 'K'},
  {mask: /krypton/g, latex: 'Kr', exp: 'Kr'},
  {mask: /lanthanum/g, latex: 'La', exp: 'La'},
  {mask: /lithium/g, latex: 'Li', exp: 'Li'},
  {mask: /lutetium/g, latex: 'Lu', exp: 'Lu'},
  {mask: /mendelevium/g, latex: 'Md', exp: 'Md'},
  {mask: /manganese/g, latex: 'Mn', exp: 'Mn'},
  {mask: /molybdenum/g, latex: 'Mo', exp: 'Mo'},
  {mask: /meitnerium/g, latex: 'Mt', exp: 'Mt'},
  {mask: /nitrogen/g, latex: 'N', exp: 'N'},
  {mask: /niobium/g, latex: 'Nb', exp: 'Nb'},
  {mask: /neodymium/g, latex: 'Nd', exp: 'Nd'},
  {mask: /neon/g, latex: 'Ne', exp: 'Ne'},
  {mask: /nickel/g, latex: 'Ni', exp: 'Ni'},
  {mask: /nobelium/g, latex: 'No', exp: 'No'},
  {mask: /neptunium/g, latex: 'Np', exp: 'Np'},
  {mask: /osmium/g, latex: 'Os', exp: 'Os'},
  {mask: /phosphorus/g, latex: 'P', exp: 'P'},
  {mask: /protactinium/g, latex: 'Pa', exp: 'Pa'},
  {mask: /lead/g, latex: 'Pb', exp: 'Pb'},
  {mask: /palladium/g, latex: 'Pd', exp: 'Pd'},
  {mask: /promethium/g, latex: 'Pm', exp: 'Pm'},
  {mask: /polonium/g, latex: 'Po', exp: 'Po'},
  {mask: /praseodymium/g, latex: 'Pr', exp: 'Pr'},
  {mask: /platinum/g, latex: 'Pt', exp: 'Pt'},
  {mask: /plutonium/g, latex: 'Pu', exp: 'Pu'},
  {mask: /radium/g, latex: 'Ra', exp: 'Ra'},
  {mask: /rutherfordium/g, latex: 'Rf', exp: 'Rf'},
  {mask: /ruthenium/g, latex: 'Ru', exp: 'Ru'},
  {mask: /sulfur/g, latex: 'S', exp: 'S'},
  {mask: /uranium/g, latex: 'U', exp: 'U'},
  {mask: /zinc/g, latex: 'Zn', exp: 'Zn'},
  {mask: /zirconium/g, latex: 'Zr', exp: 'Zr'}

];




module.exports = SIGNS;